[cisco:oi]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-oi*.log*]
SHOULD_LINEMERGE = true
sourcetype = taoi:log

[source::...ta_oi*.log*]
SHOULD_LINEMERGE = true
sourcetype = taoi:log
